create table if not exists tasks (
    id bigint generated by default as identity primary key,
    title varchar(120) not null,
    description varchar(400),
    completed boolean not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint
);

create index if not exists idx_tasks_completed on tasks (completed);
create index if not exists idx_tasks_created_at on tasks (created_at);
